# Generated by Django 5.1.7 on 2026-07-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Введенный email')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись журнала входа',
                'verbose_name_plural': 'Журнал входов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_lockout_enabled', models.BooleanField(default=True, help_text='При выключении остается только ограничение по IP на сам эндпоинт входа.', verbose_name='Блокировка аккаунта после серии неверных паролей')),
            ],
            options={
                'verbose_name': 'Настройки безопасности входа',
                'verbose_name_plural': 'Настройки безопасности входа',
            },
        ),
    ]
