# Generated by Django 5.1.7 on 2026-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP сервер')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Порт')),
                ('use_tls', models.BooleanField(default=True, verbose_name='STARTTLS')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('password_encrypted', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Пароль (зашифрован)')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='Email отправителя')),
                ('from_name', models.CharField(blank=True, default='Awareness', max_length=255, verbose_name='Имя отправителя')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Email (SMTP)',
                'verbose_name_plural': 'Настройки Email (SMTP)',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=20, verbose_name='Канал')),
                ('event', models.CharField(max_length=50, verbose_name='Событие')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('message', models.CharField(max_length=500, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись журнала уведомлений',
                'verbose_name_plural': 'Журнал уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('webhook_url_encrypted', models.CharField(blank=True, editable=False, max_length=1000, verbose_name='Webhook URL (зашифрован)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Slack',
                'verbose_name_plural': 'Настройки Slack',
            },
        ),
        migrations.CreateModel(
            name='TeamsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('webhook_url_encrypted', models.CharField(blank=True, editable=False, max_length=1000, verbose_name='Webhook URL (зашифрован)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Microsoft Teams',
                'verbose_name_plural': 'Настройки Microsoft Teams',
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('bot_token_encrypted', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Токен бота (зашифрован)')),
                ('chat_id', models.CharField(blank=True, help_text='ID группы/канала, куда бот шлет уведомления', max_length=100, verbose_name='Chat ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
    ]
