# Generated by Django 5.1.7 on 2026-07-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set', models.JSONField(help_text='Список ID вопросов, показанных в этой попытке, в показанном порядке', verbose_name='Снапшот вопросов')),
                ('pass_threshold_snapshot', models.PositiveSmallIntegerField(verbose_name='Порог сдачи на момент попытки')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('score_percent', models.FloatField(blank=True, null=True, verbose_name='Результат, %')),
                ('passed', models.BooleanField(default=False, verbose_name='Сдано')),
                ('wave_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='waves.waveassignment', verbose_name='Назначение волны')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки теста',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choices', models.JSONField(default=list, verbose_name='Выбранные варианты (ID)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='courses.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
