# Generated by Django 5.1.7 on 2026-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='forfeited_reason',
            field=models.CharField(blank=True, choices=[('focus_loss', 'Потеря фокуса на странице теста')], default='', max_length=20, verbose_name='Причина принудительного провала'),
        ),
    ]
