# Generated by Django 5.1.7 on 2026-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt_forfeited_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_control_enabled', models.BooleanField(default=True, help_text='При выключении переключение на другое окно/вкладку во время теста не отслеживается и не приводит к автоматическому провалу попытки.', verbose_name='Контроль фокуса на тесте')),
            ],
            options={
                'verbose_name': 'Настройки контроля фокуса',
                'verbose_name_plural': 'Настройки контроля фокуса',
            },
        ),
    ]
