# Generated by Django 5.1.7 on 2026-07-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_chapter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название интеграции')),
                ('prefix', models.CharField(editable=False, max_length=16, verbose_name='Префикс токена')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Токен интеграции',
                'verbose_name_plural': 'Токены интеграций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name_snapshot', models.CharField(max_length=255, verbose_name='Название токена на момент вызова')),
                ('employee_email', models.CharField(max_length=255, verbose_name='Email сотрудника')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина (от интеграции)')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('message', models.CharField(max_length=500, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course', verbose_name='Курс')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.integrationtoken', verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Запись журнала интеграции',
                'verbose_name_plural': 'Журнал интеграций',
                'ordering': ['-created_at'],
            },
        ),
    ]
