# Generated by Django 5.1.7 on 2026-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_chapter_content'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtoken',
            name='allowed_courses',
            field=models.ManyToManyField(help_text='Токен может назначать обучение только по этим курсам - ограничивает ущерб при утечке токена.', related_name='integration_tokens', to='courses.course', verbose_name='Разрешенные курсы'),
        ),
    ]
