# Generated by Django 5.1.7 on 2026-07-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Показывать лидерборды сотрудникам')),
            ],
            options={
                'verbose_name': 'Настройки лидербордов',
                'verbose_name_plural': 'Настройки лидербордов',
            },
        ),
    ]
