# Generated by Django 5.1.7 on 2026-07-05 06:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_chapter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Содержание'),
        ),
    ]
