# Generated by Django 5.1.7 on 2026-07-13 08:55

import courses.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='courses/icons/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif']), courses.validators.validate_icon_size], verbose_name='Иконка'),
        ),
    ]
