# Generated by Django 5.1.7 on 2026-07-10 18:20

import badges.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_chapter_content'),
        ('waves', '0003_waveassignment_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_real_name', models.BooleanField(default=True, verbose_name='Показывать настоящее имя на публичной странице')),
            ],
            options={
                'verbose_name': 'Настройки значков',
                'verbose_name_plural': 'Настройки значков',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='badges/icons/', verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, help_text='Выключенный значок больше не выдается, уже выданные не отзываются', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Пусто - выдается за прохождение любого курса', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='courses.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название на момент выдачи')),
                ('token', models.CharField(default=badges.models._generate_badge_token, editable=False, max_length=40, unique=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='badges.badge', verbose_name='Значок')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('wave_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='waves.waveassignment', verbose_name='Назначение волны')),
            ],
            options={
                'verbose_name': 'Выданный значок',
                'verbose_name_plural': 'Выданные значки',
                'ordering': ['-awarded_at'],
                'unique_together': {('employee', 'badge')},
            },
        ),
    ]
