# Generated by Django 5.1.7 on 2026-07-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('courses', '0003_alter_chapter_content'),
        ('waves', '0003_waveassignment_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-created_at'], 'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
        migrations.AlterModelOptions(
            name='badgesettings',
            options={'verbose_name': 'Настройки наград', 'verbose_name_plural': 'Настройки наград'},
        ),
        migrations.AlterModelOptions(
            name='employeebadge',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Выданная награда', 'verbose_name_plural': 'Выданные награды'},
        ),
        migrations.AddField(
            model_name='badge',
            name='wave',
            field=models.ForeignKey(blank=True, help_text='Указывайте для годовых/квартальных наград - награда выдастся только за прохождение именно этой волны, а не любой волны того же курса.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='waves.trainingwave', verbose_name='Волна (цикл)'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Пусто - выдается за прохождение любого курса. Игнорируется, если указана волна.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Выключенная награда больше не выдается, уже выданные не отзываются', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='employeebadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='badges.badge', verbose_name='Награда'),
        ),
    ]
