# Generated by Django 5.1.7 on 2026-07-13 06:42

import badges.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_options_alter_badgesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(upload_to='badges/icons/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif']), badges.validators.validate_icon_size], verbose_name='Иконка'),
        ),
    ]
