# Generated by Django 5.1.7 on 2026-07-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название волны')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=95, verbose_name='Порог сдачи, %')),
                ('questions_per_attempt', models.PositiveSmallIntegerField(default=15, help_text='Сколько вопросов случайно выбирается из банка вопросов курса', verbose_name='Вопросов в попытке')),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, help_text='Пусто = без ограничения', null=True, verbose_name='Макс. число попыток')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('closed', 'Закрыта')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waves', to='courses.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Волна обучения',
                'verbose_name_plural': 'Волны обучения',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WaveAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначено')),
                ('department_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department', verbose_name='Отдел на момент назначения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='waves.trainingwave', verbose_name='Волна')),
            ],
            options={
                'verbose_name': 'Назначение волны',
                'verbose_name_plural': 'Назначения волны',
                'unique_together': {('wave', 'employee')},
            },
        ),
    ]
