# Generated by Django 5.1.7 on 2026-07-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingwave',
            name='questions_per_attempt',
        ),
    ]
