# Generated by Django 5.1.7 on 2026-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_remove_trainingwave_questions_per_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveassignment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Напоминание о дедлайне шлется один раз - повторно не дублируется.', null=True, verbose_name='Напоминание отправлено'),
        ),
    ]
